### ISSUE TITLE
[User Story] As a Customer, I want to view the reviews of a business So That I can decide what to try/do

### ISSUE THREAD

**Issue by SethCKL** [goodmeh/goodmeh-frontend#10]
Can we show the Customer a Dashboard with a comprehensive yet concise display of the reviews of a business?

It should offer more information and an enhanced experience over the default google maps review page.

This page should make Customers want to use our site over the default google maps to search for a business

To do:
- [x] #5
- [x] #17
- [x] #32

**Comment by zhekaiii** [comment]
To do:
- [x] #5

**Comment by SethCKL** [comment]
This goal has been reached, i removed the time filter of reviews as a requirement as that feature just helps to enhance the view. This issue has been resolved.
