### ISSUE TITLE
Stats radar chart text cuts off on mobile

### ISSUE THREAD

**Issue by Prearo** [goodmeh/goodmeh-frontend#119]
On mobile or low-width browsers the long characteristic descriptors are cut off. Left: Desktop firefox small window. Right: Mobile chrome

<img src="https://github.com/user-attachments/assets/f0b304d4-f66c-4c7c-9b8e-46ca0af215a5" width=50%><img src="https://github.com/user-attachments/assets/30a125a0-2bf4-483f-b1d8-87a6a9e84410" width=50%>

**Comment by zhekaiii** [comment]
> This feature is not easy. we have no plan to support this feature temporarily

_Originally posted by @xile611 in https://github.com/recharts/recharts/issues/2450#issuecomment-783143765_

Only thing I can think of is shrinking the text.
![Image](https://github.com/user-attachments/assets/04bd9fcd-7fef-46ab-a3f4-c23a99194840)

**Comment by SethCKL** [comment]
![image](https://github.com/user-attachments/assets/ddde5c13-a697-4d3b-b9e7-1f0123b59a19)
temporaril fixed with a work-around.

changed the labels to single words so that we can side skirt this issue
