### ISSUE TITLE
[User Story] As a Customer, I want to be able to see all the reviews I have given, So that I can improve in the future

### ISSUE THREAD

**Issue by SethCKL** [goodmeh/goodmeh-frontend#12]
One way to improve review quality is at the source, by helping Customers themselves become better reviewers and normalizing/homogenizing their ratings

They should be able to view all reviews created by them on the platform

This is also a fun and a nice feature to help market the app (Think Spotify year in review)

This is also practical as with our Business Insight model it will also allow them to analyze their own reviews and see how they can improve as reviewers in the future

**Comment by zhekaiii** [comment]
I think we are no longer working on this right?

**Comment by SethCKL** [comment]
yes, this is no longer a priority. I will close this issue
