### ISSUE TITLE
[BUG] Recommend textbox not clearing after selecting a place

### ISSUE THREAD

**Issue by SethCKL** [goodmeh/goodmeh-frontend#122]
![image](https://github.com/user-attachments/assets/bc6aa52b-c343-4e94-9c09-4b1778c908a2)

When looking for multiple places on the recommender, after picking an option from the drop down, the text box is not cleared.

This makes it slightly annoying to search for the next place as the user has to manually clear the text box

**Comment by zhekaiii** [comment]
Wait why is your text yellow
