### ISSUE TITLE
Improve UI/UX on search pages (Discover & Compare)

### ISSUE THREAD

**Issue by SethCKL** [goodmeh/goodmeh-frontend#50]
Taking inspiration from Google's homepage, we should center the search bar on the page to direct users to easily understand their input is required

![Image](https://github.com/user-attachments/assets/b2401ff5-8e55-4a19-81dd-83999651ef90)

Upon giving the required input and the search is triggered, then give them the current view similar to how the search bar goes to the top

![Image](https://github.com/user-attachments/assets/4a6c2466-735f-4ba0-adf9-ff0a487e5783)

**Comment by zhekaiii** [comment]
![Image](https://github.com/user-attachments/assets/1957938e-e35b-459a-abda-5a2ee00f08df)
