### ISSUE TITLE
rethink layout of reviews

### ISSUE THREAD

**Issue by zhekaiii** [goodmeh/goodmeh-frontend#64]
![Image](https://github.com/user-attachments/assets/8ce47f7b-890d-4496-a88b-6b3cdd36c6a3)
not the best use of space

**Comment by zhekaiii** [comment]
I asked my friend who is a UIUX designer, here is what she said

![Image](https://github.com/user-attachments/assets/2a4d4b2d-c157-4cf6-99a8-16ffb6ff96fc)

> What do you think of putting the summary in the pink area and don't show the original? 
> Because it is cognitive overload
> if they wanna see the original they can press 'show original' somewhere in the green box
> then the red box put the pictures

**Comment by SethCKL** [comment]
![Image](https://github.com/user-attachments/assets/492822c5-b5e7-45c3-8f0b-a2965becff5d)
![Image](https://github.com/user-attachments/assets/3658a066-e3fb-4e07-9cf6-871ccb0cc414)
![Image](https://github.com/user-attachments/assets/c207a002-c800-441f-b716-6963e57ea09b)
![Image](https://github.com/user-attachments/assets/9ea8df43-fd82-4e68-98d7-71c1b15e9ba5)

Very cool previews supplied by @zhekaiii ! excited to see what you have in store for us 👀
