### ISSUE TITLE
Update PlaceComparisonTable

### ISSUE THREAD

**Issue by zhekaiii** [goodmeh/goodmeh-frontend#71]
![Image](https://github.com/user-attachments/assets/ee87f98e-39d7-491a-89ae-afd66f62a24a)

**Comment by SethCKL** [comment]
this is also awaiting https://github.com/goodmeh/goodmeh-backend/pull/161 to make use of the normalized score to aid in the display of the bars for easy comparison

**Comment by SethCKL** [comment]
> this is also awaiting [goodmeh/goodmeh-backend#161](https://github.com/goodmeh/goodmeh-backend/pull/161) to make use of the normalized score to aid in the display of the bars for easy comparison

this has been merged and this is no longer blocked, a PR has been raised with the aim to close this issue
