### ISSUE TITLE
[Bugfix] Review Insight display bar for reviews is always "full"

### ISSUE THREAD

**Issue by SethCKL** [goodmeh/goodmeh-frontend#72]
![Image](https://github.com/user-attachments/assets/73ffff9e-778c-4bf5-a5ff-f03ddb64d9cb)
as seen above, the review insight (tied to review weight) is always full for all reviews due to a change in how we calculate weight 

The scale has changed from 1-9 to 1 to 1000 for added granularity

Hence the "review insight bar" FE has to adapt to this change, and is currently always full as 9 is "still the max"

**Comment by zhekaiii** [comment]
This has been fixed
