### ISSUE TITLE
[BUG] Review Media viewer not loading images and videos

### ISSUE THREAD

**Issue by SethCKL** [goodmeh/goodmeh-frontend#84]
Photos and Videos not displaying on the review media viewer properly

Unsure if its a server issue or code issue, just logging the bug for tracking and further investigation

![image](https://github.com/user-attachments/assets/de86215b-21ed-40d7-921e-146dc63feefe)
![image](https://github.com/user-attachments/assets/a65b2f30-f423-4974-8e0e-a51389eb4bd7)

**Comment by zhekaiii** [comment]
What place is this?

**Comment by SethCKL** [comment]
for this place it was https://goodmeh.fyi/?place1Id=ChIJ3UskGbAR2jERY3FKgqm9o9w 

Ga Hock Seafood, but i think that this bug can be replicated on other if not all places

**Comment by SethCKL** [comment]
this is indeed very strange @YaleChen299 @Prearo can we get you guys to test if you can replicate? or is this a issue unique to me

**Comment by Prearo** [comment]
Can verify that **images** are not loading for:
1. Ga Hock Seafood
2. Burnt Ends Bakery (previously scraped) https://goodmeh.fyi/?place1Id=ChIJTXTgmSQb2jERRzqZmI4rLw4
3. Chef Yamashita (fresh scrape) https://goodmeh.fyi/?place1Id=ChIJ416PnmwZ2jERBp9TmiTWw6U

Result is same as in the images above - either blank or black box - when images are clicked. Both on PC and mobile.

Videos are fine (this is from Burnt Ends Bakery - plays normally and sound works)
![image](https://github.com/user-attachments/assets/4c65dda7-6d69-48f6-8648-4b01ae4652e5)

**Comment by zhekaiii** [comment]
@Prearo @SethCKL what browser are yall using?

**Comment by Prearo** [comment]
Oh I was on firefox. Not sure if it is a firefox issue? just tested other browsers and all the chromium ones (chrome, edge, samsung internet) all work fine.

**Comment by zhekaiii** [comment]
yeah I suspected it might be a firefox issue

**Comment by SethCKL** [comment]
same I am using firefox, interesting that somehow it works on other browsers but not firefox 🤷

**Comment by SethCKL** [comment]
Bug is de prioritized in light of STePS. This can be avoided by not using firefox.

Also, its a small issue and does not affect the core functionality of the app.

To be looked into after the semester
