### ISSUE TITLE
Split radar chart into related groups

### ISSUE THREAD

**Issue by zhekaiii** [goodmeh/goodmeh-frontend#90]
![Image](https://github.com/user-attachments/assets/0dd31b15-8cbb-4abe-9fa7-f8754d80961b)
Not the most user friendly to look at because I have to interpret each of the descriptors. Grouping related metrics would make it easier to interpret.

**Comment by SethCKL** [comment]
much agreed, lets revisit this issue when we have fully fine tuned the metrics (likely in the 2nd half of this sprint)
