### ISSUE TITLE
Improve compare input field clear behavior

### ISSUE THREAD

**Issue by zhekaiii** [goodmeh/goodmeh-frontend#91]
![Image](https://github.com/user-attachments/assets/a7b46581-20d4-4f62-945c-21fdd8edb503)
When you are comparing, if you click on the clear button on the right, it keeps the first place.
![Image](https://github.com/user-attachments/assets/8a507033-3004-49e3-9ef0-16d25d929bc6)

But clicking the clear button on the left clears everything. It should just clear the place on the left and keep the place on the right

**Comment by SethCKL** [comment]
agreed on this issue, tested and replicated and can echo the sentiment on the problem, as well as the intended behaviour
